# simpfun默认提供的sftp
[1a1s-sftp]
type = sftp
host = sfe4-connect.simpfun.cn
user = sfe*.*
port = 2000
pass = <yours>
disable_hashcheck = true
shell_type = none
set_modtime = false
chunk_size = 128Mi
idle_timeout = 15s
# sshd/ssld
[1a1s-ssh]
type = sftp
host = play.simpfun.cn
user = wujinjun
port = 12345
pass = <yours>
shell_type = unix
md5sum_command = /home/container/bin/busybox md5sum
sha1sum_command = /home/container/bin/busybox sha1sum
